[versions]
agp = "8.5.0"
kotlin = "2.0.21"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.3"
activityCompose = "1.9.0"
composeBom = "2024.06.00"
navVersion = "2.7.7"
viewModelVersion = "2.8.3"
roomVersion = "2.6.1"
kspVersion = "2.0.21-1.0.26"
retrofitVersion = "2.9.0"
moshiVersion = "1.15.1"
coilVersion = "2.6.0"
datastoreVersion = "1.1.1"
credentialManagerVersion = "1.2.2"
googleIdLibraryVersion = "1.1.0"
googleIdVersion = "1.1.0"
iconsExtendedVersion = "1.6.8"
imageCropperVersion = "4.5.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navVersion" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewModelVersion" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }

squareup-retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
squareup-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofitVersion" }
squareup-moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiVersion" }

io-coil-kt-coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilVersion" }

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastoreVersion" }

androidx-credential-manager = { module = "androidx.credentials:credentials", version.ref = "credentialManagerVersion" }
androidx-credential-manager-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialManagerVersion" }
google-android-gms-play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "googleIdVersion" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleIdLibraryVersion" }

androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "iconsExtendedVersion" }

canhub-cropper = { module = "com.github.CanHub:Android-Image-Cropper", version.ref = "imageCropperVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
